# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20170913_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='<django.db.models.fields.CharField><built-in function id>',
        ),
        migrations.AddField(
            model_name='country',
            name='<django.db.models.fields.CharField><django.db.models.fields.AutoField>',
            field=models.ImageField(default='', upload_to='uploads/country flags'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
