# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_auto_20170913_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='point',
            name='photo2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_point_photo2', to='points.Photo'),
        ),
        migrations.AddField(
            model_name='point',
            name='photo3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_point_photo3', to='points.Photo'),
        ),
    ]
