# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20170914_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(default='', height_field=100, upload_to='uploads/icons', width_field=100),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
