# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20170914_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(default='', upload_to='uploads/icons'),
        ),
    ]
