# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_auto_20170914_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Importence',
            new_name='Importance',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='importence',
            new_name='importance',
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='', upload_to='uploads/country flags'),
        ),
    ]
