# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=200)),
            ],
        ),
    ]
