# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20170912_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='copyright',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
