# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20170912_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='point',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='point',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='point',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.Photo'),
        ),
        migrations.AddField(
            model_name='point',
            name='trip_advisor',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='point',
            name='wiki',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='point',
            name='importence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.Importence'),
        ),
    ]
