# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20170913_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='Coordinate',
            field=models.FileField(default='', upload_to='uploads/coordinate'),
        ),
    ]
