# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_auto_20170913_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='point',
            name='city',
        ),
        migrations.RemoveField(
            model_name='point',
            name='importence',
        ),
        migrations.RemoveField(
            model_name='point',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='point',
            name='type',
        ),
        migrations.RemoveField(
            model_name='type',
            name='icon',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.DeleteModel(
            name='Importence',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
