# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_auto_20170913_1812'),
        ('routes', '0012_edge_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='point1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='edge_edges_point1', to='points.Point'),
        ),
        migrations.AddField(
            model_name='edge',
            name='point2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='edge_edges_point2', to='points.Point'),
        ),
    ]
