# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20170914_1626'),
        ('routes', '0014_auto_20170914_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(default='', height_field=100, upload_to='uploads/transports', width_field=100)),
            ],
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='point2',
            new_name='point_2',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='imp1',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='imp2',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='point1',
        ),
        migrations.AddField(
            model_name='edge',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='edge',
            name='point_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='points.Point'),
        ),
        migrations.AddField(
            model_name='edge',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='transports',
            field=models.ManyToManyField(default='', to='routes.Transport'),
        ),
    ]
