# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_auto_20170914_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='title',
        ),
        migrations.AlterField(
            model_name='transport',
            name='icon',
            field=models.ImageField(default='', upload_to='uploads/transports'),
        ),
    ]
