# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_auto_20170915_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
