# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_remove_edge_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='edge_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge2', to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge3', to='routes.Edge'),
            preserve_default=False,
        ),
    ]
