# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0019_auto_20170916_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
    ]
