# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0020_remove_route_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='edge_10',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge10', to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_4',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge4', to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_5',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge5', to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_6',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge6', to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_7',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge7', to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_8',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge8', to='routes.Edge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='edge_9',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='route_route_edge9', to='routes.Edge'),
            preserve_default=False,
        ),
    ]
