# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0021_auto_20170916_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='short_description',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
