# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0022_auto_20170916_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='point_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_edges_point2', to='points.Point'),
        ),
    ]
